server:
  port: 9001

spring:
  datasource:
    url: jdbc:tc:postgresql:11-alpine:///test
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        use-new-id-generator-mappings: true
        order_inserts: true
        ddl-auto: validate
        format_sql: false
        jdbc:
          time_zone: UTC
          batch_size: 50
